# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sebastian Meier zu Biesen's Developer Profile
email: smzb@mitos-kalandiel.me
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://smzb.mitos-kalandiel.me" # the base hostname & protocol for your site, e.g. http://example.com

username: Sebastian Meier zu Biesen
user_description: There is just a thin line between genius and insanity
user_title: Freelance IT Technician&Programmer
email: smzb@mitos-kalandiel.me
twitter_username: smeierzubiesen
github_username:  smeierzubiesen
gplus_username:  smeierzubiesen

google-analytics:
  id: ""

show_downloads: false

# Build settings
markdown: kramdown
#theme: jekyll-theme-hacker
#theme: jekyll-theme-modernist
#theme: minima
#theme: particle
gems:
  - jekyll-feed
exclude: ['package.json', 'src', 'node_modules', 'Gemfile', 'Gemfile.lock']
